//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conversation()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public string ID { get; set; }
        public string Type { get; set; }
        public string Nom { get; set; }
        public string IdEquip { get; set; }
        public string IdGroup { get; set; }
        public string IdUserCree { get; set; }
        public string IdUserContact { get; set; }
        public string LastMessage { get; set; }
        public Nullable<System.DateTime> LastMessageTime { get; set; }
        public string streamId { get; set; }
        public string conferenceId { get; set; }
        public Nullable<bool> hasStream { get; set; }
        public Nullable<bool> hasConference { get; set; }
    
        public virtual Equip Equip { get; set; }
        public virtual Group Group { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
    }
}
