//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string Id { get; set; }
        public string IdUser { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Content { get; set; }
        public string IdConversation { get; set; }
    
        public virtual User User { get; set; }
        public virtual Conversation Conversation { get; set; }
    }
}
