//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyFile
    {
        public string FileName { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FileServerName { get; set; }
        public string IdGroup { get; set; }
        public string IdEquip { get; set; }
        public string Type { get; set; }
        public Nullable<bool> ForGroup { get; set; }
    
        public virtual Equip Equip { get; set; }
        public virtual Group Group { get; set; }
    }
}
